version: "3.9"

services:
  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5434:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
    ports:
      - "5435:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  payment-service:
    image: golang:1.22
    container_name: payment-service
    working_dir: /app
    volumes:
      - ./payment-service:/app
      - ./generated:/generated
    command: sh -c "go mod download && go run ./cmd/payment-service"
    environment:
      DB_DSN: postgres://payment_user:payment_pass@payment-db:5432/payment_db?sslmode=disable
      HTTP_PORT: 8082
      GRPC_PORT: 50051
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      QUEUE_NAME: payment.completed
    depends_on:
      - payment-db
      - rabbitmq
    ports:
      - "8082:8082"
      - "50051:50051"

  order-service:
    image: golang:1.22
    container_name: order-service
    working_dir: /app
    volumes:
      - ./order-service:/app
      - ./generated:/generated
    command: sh -c "go mod download && go run ./cmd/order-service"
    environment:
      DB_DSN: postgres://order_user:order_pass@order-db:5432/order_db?sslmode=disable
      PAYMENT_SERVICE_ADDR: payment-service:50051
      HTTP_PORT: 8081
      GRPC_PORT: 50052
      REDIS_ADDR: redis:6379
    depends_on:
      - order-db
      - payment-service
      - redis
    ports:
      - "8081:8081"
      - "50052:50052"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  notification-service:
    image: golang:1.22
    container_name: notification-service
    working_dir: /app
    volumes:
      - ./notification-service:/app
    command: sh -c "go mod download && go run ./cmd/notification-service"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      QUEUE_NAME: payment.completed
      DB_DSN: postgres://notification_user:notification_pass@notification-db:5432/notification_db?sslmode=disable
      REDIS_ADDR: redis:6379
      PROVIDER_MODE: SIMULATED
    depends_on:
      - rabbitmq
      - notification-db
      - redis
    ports:
      - "8083:8083"

volumes:
  order_db_data:
  payment_db_data:
  notification_db_data:
  rabbitmq_data:
  redis_data:
